image: registry.gitlab.cc-asp.fraunhofer.de:4567/iml/oe130/software/sola/logistic-tasklanguage/lotlan_schedular:latest
stages:
  - test

unittest:
  stage: test
  script:
    - export PYTHONIOENCODING=utf-8
    - python -m xmlrunner discover -s /builds/iml/oe130/software/sola/logistic-tasklanguage/lotlan_schedular/tests -v -o ./tmp/build/junit-reports
  artifacts:
      when: always
      reports:
        junit:
            - ./tmp/build/junit-reports/*.xml
      expire_in: 1 week
  tags:
      - asprunner
