site_name: LoTLan Schedular
site_description: Documentation of the LoTLan Schedular
docs_dir: docs/
site_dir: html
markdown_extensions: [toc, fenced_code]
use_directory_urls: true 
theme:
    name: readthedocs

nav:    
    - Home: index.md
    - Installation: install.md
    - API:
        - Materialflow: api/materialflow.md
        - TransportOrder: api/transportorder.md
        - TransportOrderStep: api/transportorderstep.md
        - Location: api/location.md
        - Event: api/event.md
    - Tutorials:
        - CLI: tutorials/cli.md
    - Transport Examples: 
        - Hello Transport: tutorials/examples/hello-transport.md
        - Manual Loading/Unloading: tutorials/examples/manual-loading-unloading.md
        - Concatenation: tutorials/examples/concatenation.md
        - Infinite Loop: tutorials/examples/infinite-loop.md
        - TriggeredBy: tutorials/examples/triggered-by.md
        - FinishedBy: tutorials/examples/finished-by.md
        - Logical Operation: tutorials/examples/logical-operation.md
